version: '3.1'

networks:
  backend-net:

volumes:
  local_postgres_data_1: {}
  local_postgres_data_backups_1: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    networks:
      - backend-net

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: postgres-database
    ports:
      - "5434:5432"
    volumes:
      - local_postgres_data_1:/var/lib/postgresql/data
      - local_postgres_data_backups_1:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - backend-net

  redis:
    image: redis:3.2
    networks:
      - backend-net

  celeryworker:
    <<: *django
    image: cride_local_celeryworker
    depends_on:
      - redis
      - postgres
      
    ports: []
    command: /start-celeryworker
    networks:
      - backend-net

  celerybeat:
    <<: *django
    image: cride_local_celerybeat
    depends_on:
      - redis
      - postgres
      
    ports: []
    command: /start-celerybeat
    networks:
      - backend-net

  flower:
    <<: *django
    image: cride_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
